/**
 * API Endpoint Definitions for the API Explorer.
 * Maps to existing ENDPOINTS constants where available.
 * Endpoints marked "PENDING BACKEND VERIFICATION" have not been confirmed against the Laravel backend.
 */
import ENDPOINTS from './endpoints';

const apiEndpoints = [
  // ── Authentication ──────────────────────────────────────
  {
    id: 'auth-login',
    module: 'authentication',
    title: 'Login',
    method: 'POST',
    path: ENDPOINTS.AUTH.LOGIN,
    description: 'Authenticate user and receive access token.',
    authRequired: false,
    status: 'Ready',
    serviceFunction: 'authService.login',
    developerNotes: 'Expects { email, password } in request body.',
  },
  {
    id: 'auth-logout',
    module: 'authentication',
    title: 'Logout',
    method: 'POST',
    path: ENDPOINTS.AUTH.LOGOUT,
    description: 'Invalidate current session token.',
    authRequired: true,
    status: 'Ready',
    serviceFunction: 'authService.logout',
    developerNotes: 'Requires valid Bearer token. No request body.',
  },
  {
    id: 'auth-profile',
    module: 'authentication',
    title: 'Get Profile',
    method: 'GET',
    path: ENDPOINTS.AUTH.PROFILE,
    description: 'Retrieve authenticated user profile.',
    authRequired: true,
    status: 'Ready',
    serviceFunction: 'authService.getProfile',
    developerNotes: 'Returns user object with roles and permissions.',
  },
  {
    id: 'auth-refresh',
    module: 'authentication',
    title: 'Refresh Token',
    method: 'POST',
    path: ENDPOINTS.AUTH.REFRESH,
    description: 'Refresh expired access token.',
    authRequired: true,
    status: 'Ready',
    serviceFunction: 'authService.refreshToken',
    developerNotes: 'Uses current token to issue a new one.',
  },

  // ── Users ───────────────────────────────────────────────
  {
    id: 'users-list',
    module: 'users',
    title: 'List Users',
    method: 'GET',
    path: ENDPOINTS.USERS.BASE,
    description: 'Retrieve paginated list of users.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'userService.getUsers',
    developerNotes: 'PENDING BACKEND VERIFICATION — Supports ?page and ?search query params.',
  },
  {
    id: 'users-show',
    module: 'users',
    title: 'Get User',
    method: 'GET',
    path: ENDPOINTS.USERS.BASE + '/{id}',
    description: 'Retrieve a single user by ID.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'userService.getUserById',
    developerNotes: 'PENDING BACKEND VERIFICATION — Replace {id} with numeric user ID.',
  },
  {
    id: 'users-create',
    module: 'users',
    title: 'Create User',
    method: 'POST',
    path: ENDPOINTS.USERS.BASE,
    description: 'Create a new user account.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'userService.createUser',
    developerNotes: 'PENDING BACKEND VERIFICATION — Expects { name, email, password }.',
  },
  {
    id: 'users-update',
    module: 'users',
    title: 'Update User',
    method: 'PUT',
    path: ENDPOINTS.USERS.BASE + '/{id}',
    description: 'Update an existing user.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'userService.updateUser',
    developerNotes: 'PENDING BACKEND VERIFICATION — Partial updates with PUT.',
  },
  {
    id: 'users-delete',
    module: 'users',
    title: 'Delete User',
    method: 'DELETE',
    path: ENDPOINTS.USERS.BASE + '/{id}',
    description: 'Delete a user by ID.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'userService.deleteUser',
    developerNotes: 'PENDING BACKEND VERIFICATION — Soft delete expected.',
  },

  // ── Roles ───────────────────────────────────────────────
  {
    id: 'roles-list',
    module: 'roles',
    title: 'List Roles',
    method: 'GET',
    path: ENDPOINTS.ROLES.BASE,
    description: 'Retrieve all available roles.',
    authRequired: true,
    status: 'Coming Soon',
    serviceFunction: 'roleService.getRoles',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },
  {
    id: 'roles-show',
    module: 'roles',
    title: 'Get Role',
    method: 'GET',
    path: ENDPOINTS.ROLES.BASE + '/{id}',
    description: 'Retrieve a single role with permissions.',
    authRequired: true,
    status: 'Coming Soon',
    serviceFunction: 'roleService.getRoleById',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },
  {
    id: 'roles-create',
    module: 'roles',
    title: 'Create Role',
    method: 'POST',
    path: ENDPOINTS.ROLES.BASE,
    description: 'Create a new role.',
    authRequired: true,
    status: 'Coming Soon',
    serviceFunction: 'roleService.createRole',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },

  // ── Permissions ─────────────────────────────────────────
  {
    id: 'permissions-list',
    module: 'permissions',
    title: 'List Permissions',
    method: 'GET',
    path: ENDPOINTS.PERMISSIONS.BASE,
    description: 'Retrieve all system permissions.',
    authRequired: true,
    status: 'Coming Soon',
    serviceFunction: 'permissionService.getPermissions',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },

  // ── Articles ────────────────────────────────────────────
  {
    id: 'articles-list',
    module: 'articles',
    title: 'List Articles',
    method: 'GET',
    path: ENDPOINTS.ARTICLES.BASE,
    description: 'Retrieve paginated articles.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'articleService.getArticles',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },
  {
    id: 'articles-show',
    module: 'articles',
    title: 'Get Article',
    method: 'GET',
    path: ENDPOINTS.ARTICLES.BASE + '/{id}',
    description: 'Retrieve a single article.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'articleService.getArticleById',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },
  {
    id: 'articles-create',
    module: 'articles',
    title: 'Create Article',
    method: 'POST',
    path: ENDPOINTS.ARTICLES.BASE,
    description: 'Create a new article.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'articleService.createArticle',
    developerNotes: 'PENDING BACKEND VERIFICATION — Expects { title, body, category_id }.',
  },
  {
    id: 'articles-update',
    module: 'articles',
    title: 'Update Article',
    method: 'PUT',
    path: ENDPOINTS.ARTICLES.BASE + '/{id}',
    description: 'Update an existing article.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'articleService.updateArticle',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },
  {
    id: 'articles-delete',
    module: 'articles',
    title: 'Delete Article',
    method: 'DELETE',
    path: ENDPOINTS.ARTICLES.BASE + '/{id}',
    description: 'Delete an article.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'articleService.deleteArticle',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },

  // ── Settings ────────────────────────────────────────────
  {
    id: 'settings-list',
    module: 'settings',
    title: 'List Settings',
    method: 'GET',
    path: ENDPOINTS.SETTINGS.BASE,
    description: 'Retrieve all application settings.',
    authRequired: true,
    status: 'Ready',
    serviceFunction: 'settingService.getSettings',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },
  {
    id: 'settings-update',
    module: 'settings',
    title: 'Update Setting',
    method: 'PUT',
    path: ENDPOINTS.SETTINGS.BASE + '/{id}',
    description: 'Update a setting value.',
    authRequired: true,
    status: 'Ready',
    serviceFunction: 'settingService.updateSetting',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },

  // ── Forums ──────────────────────────────────────────────
  {
    id: 'forums-list',
    module: 'forum',
    title: 'List Threads',
    method: 'GET',
    path: ENDPOINTS.FORUMS.BASE,
    description: 'Retrieve forum threads.',
    authRequired: true,
    status: 'Coming Soon',
    serviceFunction: 'forumService.getThreads',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },
  {
    id: 'forums-show',
    module: 'forum',
    title: 'Get Thread',
    method: 'GET',
    path: ENDPOINTS.FORUMS.BASE + '/{id}',
    description: 'Retrieve a single forum thread.',
    authRequired: true,
    status: 'Coming Soon',
    serviceFunction: 'forumService.getThreadById',
    developerNotes: 'PENDING BACKEND VERIFICATION.',
  },

  // ── Categories ──────────────────────────────────────────
  {
    id: 'categories-list',
    module: 'categories',
    title: 'List Categories',
    method: 'GET',
    path: '/categories',
    description: 'Retrieve all categories.',
    authRequired: true,
    status: 'Coming Soon',
    serviceFunction: 'categoryService.getCategories',
    developerNotes: 'PENDING BACKEND VERIFICATION — Path not yet in ENDPOINTS constants.',
  },

  // ── Knowledge Base ──────────────────────────────────────
  {
    id: 'kb-list',
    module: 'knowledge-base',
    title: 'List KB Articles',
    method: 'GET',
    path: '/knowledge-base',
    description: 'Retrieve knowledge base articles.',
    authRequired: true,
    status: 'Coming Soon',
    serviceFunction: 'kbService.getArticles',
    developerNotes: 'PENDING BACKEND VERIFICATION — Path not yet in ENDPOINTS constants.',
  },

  // ── Dashboard ───────────────────────────────────────────
  {
    id: 'dashboard-stats',
    module: 'dashboard',
    title: 'Get Dashboard Stats',
    method: 'GET',
    path: '/dashboard/stats',
    description: 'Retrieve aggregated dashboard statistics.',
    authRequired: true,
    status: 'Pending',
    serviceFunction: 'dashboardService.getStats',
    developerNotes: 'PENDING BACKEND VERIFICATION — Path not yet in ENDPOINTS constants.',
  },

  // ── System ──────────────────────────────────────────────
  {
    id: 'system-health',
    module: 'system',
    title: 'Health Check',
    method: 'GET',
    path: '/system/health',
    description: 'Check backend system health.',
    authRequired: false,
    status: 'Coming Soon',
    serviceFunction: 'systemService.healthCheck',
    developerNotes: 'PENDING BACKEND VERIFICATION — Path not yet in ENDPOINTS constants.',
  },
];

export default apiEndpoints;

/**
 * Get endpoints for a specific module.
 */
export function getEndpointsByModule(moduleId) {
  return apiEndpoints.filter(ep => ep.module === moduleId);
}
